import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Disorienting Roar': new Skill('Disorienting Roar', 1, 17,
        halfCard([Tag.MUDDLE, Tag.IMMOBILIZE, Tag.RANGED, Tag.XP]), 
        halfCard([Tag.DISCARD])),
    'Spirit Swap': new Skill('Spirit Swap', 1, 22,
        halfCard([Tag.MOVE, Tag.XP]), 
        halfCard([])),
    'Venomous Ally': new Skill('Venomous Ally', 1, 79,
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.RANGED, Tag.POISON])),
    'Relentless Ally': new Skill('Relentless Ally', 1, 81,
        halfCard([Tag.SUMMON, Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Concentrated Rage': new Skill('Concentrated Rage', 1, 51,
        halfCard([Tag.RANGED, Tag.DISARM]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.DISCARD])),
    'Disappearing Wounds': new Skill('Disappearing Wounds', 1, 23,
        halfCard([Tag.HEAL]), 
        halfCard([Tag.MELEE, Tag.XP])),
    'Patch Fur': new Skill('Patch Fur', 1, 20,
        halfCard([Tag.SINGLE_ROUND_BUFF, Tag.SHIELD]), 
        halfCard([Tag.HEAL, Tag.XP])),
    'Maul': new Skill('Maul', 1, 14,
        halfCard([Tag.MELEE]), 
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Forceful Swipe': new Skill('Forceful Swipe', 1, 35,
        halfCard([Tag.MELEE, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.PUSH, Tag.XP])),
    'Howling Bolts': new Skill('Howling Bolts', 1, 47,
        halfCard([Tag.RANGED, Tag.AOE]), 
        halfCard([Tag.MOVE])),
    'Soaring Ally': new Skill('Soaring Ally', 0, 77,
        halfCard([Tag.SUMMON, Tag.GENERATE_AIR, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.JUMP])),
    'Focused Aggression': new Skill('Focused Aggression', 0, 31,
        halfCard([Tag.RANGED]), 
        halfCard([Tag.MELEE, Tag.GENERATE_EARTH, Tag.XP, Tag.DISCARD])),
    'Borrowed Essence': new Skill('Borrowed Essence', 0, 56,
        halfCard([Tag.RANGED, Tag.CONSUME_AIR, Tag.HEAL, Tag.CONSUME_EARTH, Tag.XP]), 
        halfCard([])),
    'Energizing Strike': new Skill('Energizing Strike', 2, 29,
        halfCard([Tag.MELEE, Tag.STRENGTHEN, Tag.XP]), 
        halfCard([Tag.HEAL])),
    'Earthen Spikes': new Skill('Earthen Spikes', 2, 11,
        halfCard([Tag.RANGED, Tag.IMMOBILIZE, Tag.GENERATE_EARTH]), 
        halfCard([Tag.SHIELD, Tag.RETALIATE, Tag.SINGLE_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Vicious Ally': new Skill('Vicious Ally', 3, 86,
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MELEE, Tag.AOE, Tag.XP])),
    'Unstoppable Beast': new Skill('Unstoppable Beast', 3, 32,
        halfCard([Tag.MELEE, Tag.CONSUME_EARTH, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE])),
    'Ancient Ward': new Skill('Ancient Ward', 4, 19,
        halfCard([Tag.RANGED, Tag.AOE, Tag.DISARM, Tag.XP]), 
        halfCard([Tag.HEAL])),
    'Punch Through': new Skill('Punch Through', 4, 44,
        halfCard([Tag.MELEE, Tag.PIERCE, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.SINGLE_ROUND_BUFF])),
    'Rampage': new Skill('Rampage', 5, 34,
        halfCard([Tag.MELEE, Tag.MOVE, Tag.XP, Tag.DISCARD]), 
        halfCard([])),
    'Stone Sigil': new Skill('Stone Sigil', 5, 95,
        halfCard([Tag.SUMMON, Tag.GENERATE_EARTH, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Primal Blessing': new Skill('Primal Blessing', 6, 28,
        halfCard([Tag.HEAL, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE])),
    'Blood Hunger': new Skill('Blood Hunger', 6, 42,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.HEAL, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MELEE, Tag.HEAL, Tag.XP])),
    'Storm Sigil': new Skill('Storm Sigil', 7, 93,
        halfCard([Tag.SUMMON, Tag.GENERATE_AIR, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MELEE])),
    'Tyrannical Force': new Skill('Tyrannical Force', 7, 37,
        halfCard([Tag.RANGED, Tag.STUN, Tag.GENERATE_EARTH]), 
        halfCard([])),
    'Lash Out': new Skill('Lash Out', 8, 18,
        halfCard([Tag.MELEE, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.PUSH, Tag.AOE, Tag.XP])),
    'Natural Remedy': new Skill('Natural Remedy', 8, 25,
        halfCard([Tag.HEAL, Tag.CONSUME_AIR, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.STRENGTHEN])),
    'Jaws of Death': new Skill('Jaws of Death', 9, 48,
        halfCard([Tag.INSTA_KILL, Tag.XP]), 
        halfCard([Tag.MELEE, Tag.PUSH, Tag.MOVE, Tag.XP])),
    'Tribal Sigil': new Skill('Tribal Sigil', 9, 91,
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([]))
};

export default class BeastTyrant extends Class {

    constructor() {
        super('Beast Tyrant', 10, HitpointsScaling.SQUISHY, true, skills);
    }
}
