import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Raw Enhancement': new Skill('Raw Enhancement', 1, 48,
        halfCard([Tag.RANGED, Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.CONSUME_ICE, Tag.CONSUME_EARTH, Tag.XP])),
    'Pure Augmentation': new Skill('Pure Augmentation', 1, 48,
        halfCard([Tag.RANGED, Tag.CONSUME_EARTH, Tag.CONSUME_ICE, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.CONSUME_AIR, Tag.CONSUME_FIRE, Tag.XP])),
    'Formless Power': new Skill('Formless Power', 1, 45,
        halfCard([Tag.RANGED, Tag.CONSUME_ANY, Tag.XP]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.CONSUME_ANY, Tag.DISCARD])),
    'Shaping the Ether': new Skill('Shaping the Ether', 1, 54,
        halfCard([Tag.RANGED, Tag.XP, Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.CONSUME_ICE, Tag.CONSUME_EARTH, Tag.PUSH, Tag.STUN, Tag.AOE]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.GENERATE_ANY, Tag.DISCARD])),
    'Stoking Hail': new Skill('Stoking Hail', 1, 28,
        halfCard([Tag.RANGED, Tag.CONSUME_ICE, Tag.STUN, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.GENERATE_FIRE])),
    'Tremulant Cyclone': new Skill('Tremulant Cyclone', 1, 26,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_AIR, Tag.PUSH, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.GENERATE_EARTH])),
    'Infernal Vortex': new Skill('Infernal Vortex', 1, 17,
        halfCard([Tag.RANGED, Tag.GENERATE_FIRE, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.GENERATE_ICE])),
    'Lava Eruption': new Skill('Lava Eruption', 1, 19,
        halfCard([Tag.RANGED, Tag.GENERATE_FIRE, Tag.GENERATE_EARTH, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.GENERATE_AIR])),
    'Ice Spikes': new Skill('Ice Spikes', 1, 40,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_FIRE, Tag.WOUND, Tag.XP]), 
        halfCard([Tag.RANGED, Tag.IMMOBILIZE, Tag.GENERATE_ICE, Tag.GENERATE_EARTH, Tag.XP, Tag.DISCARD])),
    'Frigid Torrent': new Skill('Frigid Torrent', 1, 35,
        halfCard([Tag.MELEE, Tag.CONSUME_EARTH, Tag.AOE, Tag.PIERCE, Tag.XP]), 
        halfCard([Tag.RANGED, Tag.AOE, Tag.PULL, Tag.GENERATE_ICE, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD])),
    'Malleable Evocation': new Skill('Malleable Evocation', 0, 50,
        halfCard([Tag.RANGED, Tag.XP, Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.CONSUME_ICE, Tag.CONSUME_EARTH, Tag.WOUND, Tag.AOE, Tag.IMMOBILIZE, Tag.POISON]), 
        halfCard([Tag.MOVE, Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.CONSUME_ICE, Tag.CONSUME_EARTH, Tag.JUMP, Tag.HEAL, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Brilliant Flash': new Skill('Brilliant Flash', 0, 67,
        halfCard([Tag.HEAL, Tag.GENERATE_LIGHT]), 
        halfCard([Tag.LOOT])),
    'Encompassing Shadow': new Skill('Encompassing Shadow', 0, 23,
        halfCard([Tag.INVISIBLE, Tag.GENERATE_DARK]), 
        halfCard([Tag.MOVE, Tag.SINGLE_ROUND_BUFF])),
    'Boiling Arc': new Skill('Boiling Arc', 2, 47,
        halfCard([Tag.MELEE, Tag.AOE, Tag.GENERATE_FIRE]), 
        halfCard([Tag.MOVE, Tag.CONSUME_FIRE, Tag.RETALIATE, Tag.SINGLE_ROUND_BUFF])),
    'Crystallizing Blast': new Skill('Crystallizing Blast', 2, 67,
        halfCard([Tag.RANGED, Tag.AOE, Tag.GENERATE_ICE]), 
        halfCard([Tag.MOVE, Tag.CONSUME_ICE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Burial': new Skill('Burial', 3, 65,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_EARTH, Tag.CONSUME_DARK, Tag.IMMOBILIZE, Tag.CURSE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.RANGED, Tag.GENERATE_DARK])),
    'Chain Lightning': new Skill('Chain Lightning', 3, 41,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_LIGHT, Tag.CONSUME_AIR, Tag.PIERCE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.HEAL, Tag.GENERATE_LIGHT])),
    'Primal Duality': new Skill('Primal Duality', 4, 15,
        halfCard([Tag.RANGED, Tag.AOE, Tag.GENERATE_ICE, Tag.GENERATE_FIRE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.GENERATE_LIGHT, Tag.GENERATE_DARK])),
    'Gravel Vortex': new Skill('Gravel Vortex', 4, 62,
        halfCard([Tag.MELEE, Tag.GENERATE_AIR, Tag.GENERATE_EARTH]), 
        halfCard([Tag.LOOT, Tag.CONSUME_ANY])),
    'Obsidian Shards': new Skill('Obsidian Shards', 5, 36,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_FIRE, Tag.CONSUME_EARTH, Tag.XP]), 
        halfCard([Tag.SHIELD, Tag.GENERATE_ICE, Tag.GENERATE_DARK, Tag.SINGLE_ROUND_BUFF])),
    'Winter\'s Edge': new Skill('Winter\'s Edge', 5, 43,
        halfCard([Tag.RANGED, Tag.CONSUME_ICE, Tag.CONSUME_AIR, Tag.PIERCE, Tag.XP]), 
        halfCard([Tag.HEAL, Tag.GENERATE_FIRE, Tag.GENERATE_LIGHT])),
    'Eye of the Hurricane': new Skill('Eye of the Hurricane', 6, 29,
        halfCard([Tag.HEAL, Tag.RANGED, Tag.GENERATE_ICE, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.JUMP, Tag.XP])),
    'Simulacrum': new Skill('Simulacrum', 6, 94,
        halfCard([Tag.RANGED, Tag.CONSUME_ANY, Tag.AOE, Tag.IMMOBILIZE, Tag.MUDDLE, Tag.XP]), 
        halfCard([Tag.SUMMON, Tag.GENERATE_EARTH, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD])),
    'Vengeance': new Skill('Vengeance', 7, 33,
        halfCard([Tag.RANGED, Tag.CONSUME_DARK, Tag.CONSUME_ANY, Tag.INSTA_KILL, Tag.XP, Tag.AOE]), 
        halfCard([Tag.MOVE, Tag.RETALIATE, Tag.CONSUME_LIGHT, Tag.CONSUME_ANY, Tag.XP, Tag.SINGLE_ROUND_BUFF])),
    'Pragmatic Reinforcement': new Skill('Pragmatic Reinforcement', 7, 56,
        halfCard([Tag.HEAL, Tag.XP, Tag.CONSUME_ICE, Tag.CONSUME_EARTH, Tag.CONSUME_LIGHT, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF]), 
        halfCard([Tag.RANGED, Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.CONSUME_DARK, Tag.POISON, Tag.WOUND])),
    'Volatile Consumption': new Skill('Volatile Consumption', 8, 64,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD, Tag.HEAL]), 
        halfCard([Tag.MOVE, Tag.JUMP, Tag.CONSUME_FIRE, Tag.CONSUME_ICE, Tag.CONSUME_ANY, Tag.WOUND, Tag.IMMOBILIZE, Tag.XP])),
    'Elemental Aegis': new Skill('Elemental Aegis', 8, 14,
        halfCard([Tag.SHIELD, Tag.SINGLE_ROUND_BUFF, Tag.CONSUME_ANY, Tag.XP]), 
        halfCard([Tag.HEAL, Tag.GENERATE_LIGHT])),
    'Ethereal Manifestation': new Skill('Ethereal Manifestation', 9, 98,
        halfCard([Tag.SUMMON, Tag.XP, Tag.CONSUME_DARK, Tag.DISCARD]), 
        halfCard([Tag.CONSUME_FIRE, Tag.CONSUME_AIR, Tag.CONSUME_ICE, Tag.CONSUME_EARTH, Tag.RANGED, Tag.MOVE, Tag.LOOT, Tag.HEAL])),
    'Eternal Equilibrium': new Skill('Eternal Equilibrium', 9, 27,
        halfCard([Tag.RANGED, Tag.CONSUME_DARK, Tag.CONSUME_LIGHT, Tag.AOE, Tag.CURSE, Tag.MUDDLE, Tag.XP]), 
        halfCard([Tag.HEAL, Tag.CONSUME_FIRE, Tag.CONSUME_ICE, Tag.RETALIATE, Tag.SHIELD, Tag.XP, Tag.SINGLE_ROUND_BUFF])),
};

export default class Elementalist extends Class {

    constructor() {
        super('Elementalist', 10, HitpointsScaling.SQUISHY, true, skills);
    }
}
