import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Black Knives': new Skill('Black Knives', 1, 44, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MELEE, Tag.MUDDLE, Tag.XP])),
    'Cloak of Shade': new Skill('Cloak of Shade', 1, 13, 
        halfCard([Tag.MELEE, Tag.GENERATE_DARK]), 
        halfCard([Tag.MOVE, Tag.CONSUME_DARK, Tag.INVISIBLE, Tag.XP])),
    'Empowering Void': new Skill('Empowering Void', 1, 21, 
        halfCard([Tag.MELEE, Tag.CONSUME_DARK, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.CONSUME_DARK, Tag.XP])),
    'Doomed Breeze': new Skill('Doomed Breeze', 1, 15, 
        halfCard([Tag.RANGED, Tag.MUDDLE, Tag.GENERATE_DARK, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.CURSE])),
    'Enervating Wound': new Skill('Enervating Wound', 1, 77, 
        halfCard([Tag.MELEE, Tag.WOUND, Tag.HEAL, Tag.GENERATE_DARK, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Spirit of the Night': new Skill('Spirit of the Night', 1, 84, 
        halfCard([Tag.MELEE, Tag.CONSUME_DARK, Tag.INSTA_KILL, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.GENERATE_DARK, Tag.XP, Tag.DISCARD])),
    'Dancing Shadows': new Skill('Dancing Shadows', 1, 9, 
        halfCard([Tag.MOVE, Tag.MELEE]), 
        halfCard([Tag.SINGLE_ROUND_BUFF, Tag.GENERATE_DARK])),
    'Silent Force': new Skill('Silent Force', 1, 91, 
        halfCard([Tag.MELEE, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.LOOT, Tag.DISCARD])),
    'Smoke Step': new Skill('Smoke Step', 1, 28, 
        halfCard([Tag.MOVE, Tag.MELEE, Tag.CONSUME_DARK, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.GENERATE_DARK])),
    'Wings of the Night': new Skill('Wings of the Night', 0, 24, 
        halfCard([Tag.MELEE, Tag.INVISIBLE]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Concealed Dominance': new Skill('Concealed Dominance', 0, 35, 
        halfCard([Tag.MELEE, Tag.CONSUME_DARK, Tag.AOE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.CONSUME_DARK, Tag.DISCARD])),
    'Dark Cloud': new Skill('Dark Cloud', 0, 74, 
        halfCard([Tag.MELEE, Tag.CURSE]), 
        halfCard([Tag.MUDDLE, Tag.AOE, Tag.GENERATE_DARK])),
    'Prepare for the Kill': new Skill('Prepare for the Kill', 2, 7,
        halfCard([Tag.MELEE, Tag.GENERATE_DARK]), 
        halfCard([Tag.MOVE, Tag.GENERATE_DARK])),
    'Soulfire': new Skill('Soulfire', 2, 85,
        halfCard([Tag.RANGED, Tag.WOUND, Tag.STUN, Tag.XP]), 
        halfCard([Tag.MELEE, Tag.CURSE, Tag.DISCARD])),
    'Terror Blade': new Skill('Terror Blade', 3, 17,
        halfCard([Tag.MELEE, Tag.PUSH]), 
        halfCard([Tag.MOVE, Tag.SINGLE_ROUND_BUFF])),
    'Armor of the Night': new Skill('Armor of the Night', 3, 23,
        halfCard([Tag.MELEE, Tag.CONSUME_DARK, Tag.HEAL, Tag.XP]),
        halfCard([Tag.SHIELD, Tag.GENERATE_DARK, Tag.SINGLE_ROUND_BUFF])),
    'Nightfall': new Skill('Nightfall', 4, 73,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.GENERATE_DARK, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.MELEE, Tag.CONSUME_LIGHT, Tag.GENERATE_DARK, Tag.XP])),
    'Grim Sustenance': new Skill('Grim Sustenance', 4, 29,
        halfCard([Tag.MELEE, Tag.XP, Tag.INVISIBLE]), 
        halfCard([Tag.LOOT, Tag.GENERATE_DARK])),
    'Claws of the Night': new Skill('Claws of the Night', 5, 26,
        halfCard([Tag.MELEE, Tag.POISON, ...Tag.CONSUME_ANY, Tag.GENERATE_DARK, Tag.XP, Tag.AOE]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Black Arrow': new Skill('Black Arrow', 5, 11,
        halfCard([Tag.RANGED, Tag.MUDDLE, Tag.CURSE, Tag.XP]), 
        halfCard([Tag.INVISIBLE, Tag.CONSUME_DARK, Tag.RANGED, Tag.XP])),
    'Unseen Dread': new Skill('Unseen Dread', 6, 5,
        halfCard([Tag.MELEE, Tag.GENERATE_DARK]), 
        halfCard([Tag.MOVE, Tag.JUMP])),
    'Swallowed by Fear': new Skill('Swallowed by Fear', 6, 90,
        halfCard([Tag.MELEE, ...Tag.CONSUME_ANY, Tag.INSTA_KILL, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.PUSH, Tag.AOE])),
    'Eyes of the Night': new Skill('Eyes of the Night', 7, 35,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.CONSUME_LIGHT, Tag.MUDDLE, Tag.AOE, Tag.GENERATE_DARK, Tag.XP])),
    'Quiet Frenzy': new Skill('Quiet Frenzy', 7, 19,
        halfCard([Tag.MELEE, Tag.XP, Tag.CONSUME_DARK]), 
        halfCard([Tag.MELEE, Tag.MOVE])),
    'Gloom Darts': new Skill('Gloom Darts', 8, 78,
        halfCard([Tag.RANGED, Tag.POISON, Tag.CURSE, Tag.CONSUME_DARK, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.GENERATE_DARK])),
    'Lurking Ruin': new Skill('Lurking Ruin', 8, 18,
        halfCard([Tag.MELEE, Tag.POISON, Tag.MUDDLE, Tag.WOUND, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.INVISIBLE])),
    'Angel of Death': new Skill('Angel of Death', 9, 38,
        halfCard([Tag.MELEE, Tag.AOE, Tag.CONSUME_DARK, Tag.INSTA_KILL, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.JUMP, Tag.CONSUME_DARK, Tag.INSTA_KILL, Tag.XP])),
    'Voice of the Night': new Skill('Voice of the Night', 9, 6,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.STUN, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.MELEE, ...Tag.CONSUME_ANY, Tag.INVISIBLE, Tag.GENERATE_DARK, Tag.XP]))
};

export default class Nightshroud extends Class {

    constructor() {
        super('Nightshroud', 9, HitpointsScaling.MIDRANGE, true, skills);
    }
}
