import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Vile Pestilence': new Skill('Vile Pestilence', 1, 61, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.POISON]),
        halfCard([Tag.MOVE])),
    'Grasping Vermin': new Skill('Grasping Vermin', 1, 69, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.IMMOBILIZE]),
        halfCard([Tag.SHIELD, Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Wretched Swarm': new Skill('Wretched Swarm', 1, 84, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.STUN, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Spread the Plague': new Skill('Spread the Plague', 1, 27, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.RANGED])),
    'Biting Gnats': new Skill('Biting Gnats', 1, 47,
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]),
        halfCard([Tag.MOVE])),
    'Winged Congregation': new Skill('Winged Congregation', 1, 16,
        halfCard([Tag.FLYING, Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.GENERATE_AIR, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.HEAL])),
    'Creeping Curse': new Skill('Creeping Curse', 1, 72,
        halfCard([Tag.RANGED, Tag.CURSE]),
        halfCard([Tag.MOVE, Tag.CURSE])),
    'Gathering Doom': new Skill('Gathering Doom', 1, 76,
        halfCard([Tag.RANGED, Tag.CURSE]),
        halfCard([Tag.LOOT, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD])),
    'Paralyzing Bite': new Skill('Paralyzing Bite', 1, 31,
        halfCard([Tag.RANGED, Tag.STUN, Tag.XP]),
        halfCard([Tag.MOVE, Tag.JUMP, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD])),
    'Foul Wind': new Skill('Foul Wind', 1, 35,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.LOOT])),
    'Scattered Terror': new Skill('Scattered Terror', 1, 11,
        halfCard([Tag.RANGED, Tag.AOE, Tag.PIERCE, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Epidemic': new Skill('Epidemic', 0, 43,
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]),
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.POISON, Tag.XP, Tag.DISCARD])),
    'Virulent Strain': new Skill('Virulent Strain', 0, 50,
        halfCard([Tag.XP]),
        halfCard([Tag.POISON])),
    'Blistering Vortex': new Skill('Blistering Vortex', 0, 21,
        halfCard([Tag.RANGED, Tag.AOE, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Under the Skin': new Skill('Under the Skin', 2, 59,
        halfCard([Tag.RANGED, Tag.PIERCE, Tag.XP]),
        halfCard([Tag.MOVE])),
    'Rot Maggots': new Skill('Rot Maggots', 2, 69,
        halfCard([Tag.RANGED, Tag.POISON, Tag.XP]),
        halfCard([Tag.HEAL])),
    'Succumb to the Gift': new Skill('Succumb to the Gift', 3, 70,
        halfCard([Tag.INSTA_KILL, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.BLESS])),
    'Fetid Flurry': new Skill('Fetid Flurry', 3, 26,
        halfCard([Tag.RANGED, Tag.CURSE]),
        halfCard([Tag.MOVE, Tag.GENERATE_AIR])),
    'Storm of Wings': new Skill('Storm of Wings', 4, 91,
        halfCard([Tag.RANGED, Tag.CONSUME_AIR, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Nightmarish Affliction': new Skill('Nightmarish Affliction', 4, 43,
        halfCard([Tag.RANGED, Tag.AOE, Tag.POISON, Tag.CURSE, Tag.GENERATE_DARK]),
        halfCard([Tag.IMMOBILIZE])),
    'Accelerated End': new Skill('Accelerated End', 5, 62,
        halfCard([Tag.CONSUME_DARK, Tag.XP]),
        halfCard([Tag.POISON])),
    'Willing Sacrifice': new Skill('Willing Sacrifice', 5, 84,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.CONSUME_AIR, Tag.XP, Tag.DISCARD])),
    'Stinging Cloud': new Skill('Stinging Cloud', 6, 66,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_DARK, Tag.MUDDLE, Tag.XP]),
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Black Tides': new Skill('Black Tides', 6, 37,
        halfCard([Tag.RANGED, Tag.GENERATE_AIR]),
        halfCard([Tag.MOVE, Tag.GENERATE_DARK])),
    'Airborne Toxin': new Skill('Airborne Toxin', 7, 57,
        halfCard([Tag.CURSE, Tag.MUDDLE, Tag.CONSUME_AIR, Tag.XP]),
        halfCard([Tag.POISON, Tag.GENERATE_AIR, Tag.XP, Tag.DISCARD])),
    'Baneful Hex': new Skill('Baneful Hex', 7, 33,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.CURSE])),
    'Spreading Scourge': new Skill('Spreading Scourge', 8, 71,
        halfCard([Tag.RANGED, Tag.MUDDLE]),
        halfCard([Tag.HEAL])),
    'Grim Bargain': new Skill('Grim Bargain', 8, 46,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.GENERATE_DARK, Tag.XP, Tag.SINGLE_ROUND_BUFF, Tag.DISCARD])),
    'Mass Extinction': new Skill('Mass Extinction', 9, 94,
        halfCard([Tag.CURSE, Tag.WOUND, Tag.GENERATE_AIR, Tag.GENERATE_DARK]),
        halfCard([Tag.CONSUME_AIR, Tag.CONSUME_DARK, Tag.XP])),
    'Convert the Flock': new Skill('Convert the Flock', 9, 29,
        halfCard([Tag.RANGED, Tag.AOE, Tag.CURSE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.SINGLE_ROUND_BUFF, Tag.XP])),
};

export default class Plagueherald extends Class {

    constructor() {
        super('Plagueherald', 11, HitpointsScaling.SQUISHY, true, skills);
    }
}
