import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Restock': new Skill('Restock', 1, 73,
        halfCard([Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MELEE])),
    'Oversized Pack': new Skill('Oversized Pack', 1, 81,
        halfCard([Tag.LOOT]), 
        halfCard([Tag.XP, Tag.DISCARD])),
    'Sharpening Kit': new Skill('Sharpening Kit', 1, 23,
        halfCard([Tag.HEAL, Tag.XP]), 
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Proficiency': new Skill('Proficiency', 1, 62,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Iron Bulwark': new Skill('Iron Bulwark', 1, 19,
        halfCard([Tag.MELEE, Tag.MUDDLE]), 
        halfCard([Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Hastened Step': new Skill('Hastened Step', 1, 26,
        halfCard([Tag.MELEE, Tag.MOVE]), 
        halfCard([Tag.MOVE])),
    'Cleaving Axe': new Skill('Cleaving Axe', 1, 52,
        halfCard([Tag.MELEE, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE])),
    'Impaling Spear': new Skill('Impaling Spear', 1, 48,
        halfCard([Tag.MELEE, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE])),
    'Crippling Bow': new Skill('Crippling Bow', 1, 44,
        halfCard([Tag.RANGED, Tag.XP]), 
        halfCard([Tag.RANGED, Tag.IMMOBILIZE])),
    'Crushing Hammer': new Skill('Crushing Hammer', 0, 17,
        halfCard([Tag.MELEE, Tag.STUN, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Scroll of Recall': new Skill('Scroll of Recall', 0, 98,
        halfCard([]), 
        halfCard([Tag.PULL, Tag.RANGED, Tag.AOE])),
    'Reserved Energy': new Skill('Reserved Energy', 0, 88,
        halfCard([Tag.XP]), 
        halfCard([Tag.MOVE])),
    'Reforge': new Skill('Reforge', 2, 95,
        halfCard([Tag.XP]), 
        halfCard([])),
    'Bladed Boomerang': new Skill('Bladed Boomerang', 2, 40,
        halfCard([Tag.RANGED, Tag.WOUND, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.MELEE])),
    'Continual Supply': new Skill('Continual Supply', 3, 86,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.DISCARD])),
    'Scroll of Lightning': new Skill('Scroll of Lightning', 3, 77,
        halfCard([Tag.RANGED, Tag.GENERATE_LIGHT]), 
        halfCard([Tag.MOVE, Tag.PUSH, Tag.AOE, Tag.GENERATE_AIR])),
    'Side Pouch': new Skill('Side Pouch', 4, 84,
        halfCard([Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.LOOT])),
    'Giant Club': new Skill('Giant Club', 4, 61,
        halfCard([Tag.MELEE, Tag.XP]), 
        halfCard([Tag.MELEE, Tag.MUDDLE])),
    'Reinforced Steel': new Skill('Reinforced Steel', 5, 12,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Scroll of Judgment': new Skill('Scroll of Judgment', 5, 66,
        halfCard([Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.STUN])),
    'Catastrophic Bomb': new Skill('Catastrophic Bomb', 6, 46,
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]), 
        halfCard([Tag.AOE, Tag.XP])),
    'Quiver of Arrows': new Skill('Quiver of Arrows', 6, 31,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Scroll of Blizzards': new Skill('Scroll of Blizzards', 7, 46,
        halfCard([Tag.RANGED, Tag.AOE, Tag.GENERATE_ICE]), 
        halfCard([Tag.IMMOBILIZE, Tag.AOE, Tag.MOVE, Tag.GENERATE_DARK])),
    'Refreshment': new Skill('Refreshment', 7, 89,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.XP, Tag.DISCARD])),
    'Portable Ballista': new Skill('Portable Ballista', 8, 41,
        halfCard([Tag.MELEE, Tag.AOE, Tag.XP]), 
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Fortified Position': new Skill('Fortified Position', 8, 10,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.HEAL, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Scroll of Annihilation': new Skill('Scroll of Annihilation', 9, 56,
        halfCard([Tag.INSTA_KILL, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.DISARM, Tag.AOE])),
    'Bag of Holding': new Skill('Bag of Holding', 9, 91,
        halfCard([Tag.LOOT]), 
        halfCard([Tag.XP, Tag.DISCARD]))
};

export default class Quartermaster extends Class {

    constructor() {
        super('Quartermaster', 9, HitpointsScaling.TANK, true, skills);
    }
}
