import Class from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Single Out': new Skill('Single Out', 1, 86, 
        halfCard([Tag.MELEE, Tag.XP]),
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Flanking Strike': new Skill('Flanking Strike', 1, 4, 
        halfCard([Tag.MELEE, Tag.XP]),
        halfCard([Tag.MOVE])),
    'Smoke Bomb': new Skill('Smoke Bomb', 1, 12, 
        halfCard([Tag.INVISIBLE, Tag.GENERATE_DARK, Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.PULL])),
    'Backstab': new Skill('Backstab', 1, 6, 
        halfCard([Tag.MELEE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Thief\'s Knack': new Skill('Thief\'s Knack', 1, 23, 
        halfCard([Tag.XP]),
        halfCard([Tag.MELEE, Tag.XP])),
    'Venom Shiv': new Skill('Venom Shiv', 1, 60, 
        halfCard([Tag.MELEE, Tag.POISON, Tag.XP]),
        halfCard([Tag.MOVE])),
    'Throwing Knives': new Skill('Throwing Knives', 1, 10, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]),
        halfCard([Tag.LOOT])),
    'Quick Hands': new Skill('Quick Hands', 1, 64, 
        halfCard([Tag.MOVE, Tag.MELEE]),
        halfCard([Tag.LOOT])),
    'Special Mixture': new Skill('Special Mixture', 1, 33, 
        halfCard([Tag.HEAL]),
        halfCard([Tag.MOVE, Tag.POISON])),
    'Sinister Opportunity': new Skill('Sinister Opportunity', 0, 93, 
        halfCard([Tag.MELEE, Tag.CONSUME_DARK, Tag.XP]),
        halfCard([Tag.MOVE])),
    'Trickster\'s Reversal': new Skill('Trickster\'s Reversal', 0, 9, 
        halfCard([Tag.MELEE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Swift Bow': new Skill('Swift Bow', 0, 36, 
        halfCard([Tag.RANGED]),
        halfCard([Tag.MOVE, Tag.LOOT])),
    'Open Wound': new Skill('Open Wound', 2, 11, 
        halfCard([Tag.MELEE, Tag.WOUND, Tag.XP]),
        halfCard([Tag.MOVE])),
    'Flintlock': new Skill('Flintlock', 2, 90, 
        halfCard([Tag.LOOT]),
        halfCard([Tag.RANGED, Tag.XP, Tag.DISCARD])),
    'Hidden Daggers': new Skill('Hidden Daggers', 3, 85, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.INVISIBLE])),
    'Duelist\'s Advance': new Skill('Duelist\'s Advance', 3, 16, 
        halfCard([Tag.MOVE, Tag.MELEE]),
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Flurry of Blades': new Skill('Flurry of Blades', 4, 3, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]),
        halfCard([Tag.MOVE, Tag.SINGLE_ROUND_BUFF])),
    'Gruesome Advantage': new Skill('Gruesome Advantage', 4, 62, 
        halfCard([Tag.MELEE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Cull the Weak': new Skill('Cull the Weak', 5, 16, 
        halfCard([Tag.MELEE, Tag.XP]),
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Visage of the Inevitable': new Skill('Visage of the Inevitable', 5, 88, 
        halfCard([Tag.INSTA_KILL, Tag.XP]),
        halfCard([Tag.MOVE, Tag.POISON, Tag.AOE])),
    'Crippling Poison': new Skill('Crippling Poison', 6, 30, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.DISCARD]),
        halfCard([Tag.MELEE, Tag.POISON, Tag.IMMOBILIZE, Tag.XP])),
    'Burning Oil': new Skill('Burning Oil', 6, 95, 
        halfCard([Tag.RANGED, Tag.WOUND, Tag.GENERATE_FIRE, Tag.XP]),
        halfCard([Tag.LOOT, Tag.XP])),
    'Stick to the Shadows': new Skill('Stick to the Shadows', 7, 26, 
        halfCard([Tag.MELEE, Tag.CONSUME_DARK, Tag.XP]),
        halfCard([Tag.MOVE, Tag.INVISIBLE])),
    'Spring the Trap': new Skill('Spring the Trap', 7, 13, 
        halfCard([Tag.XP]),
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Stiletto Storm': new Skill('Stiletto Storm', 8, 80, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]),
        halfCard([Tag.MOVE, Tag.RETALIATE, Tag.SINGLE_ROUND_BUFF])),
    'Pain\'s End': new Skill('Pain\'s End', 8, 38, 
        halfCard([Tag.HEAL, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.INSTA_KILL])),
    'Long Con': new Skill('Long Con', 9, 2, 
        halfCard([Tag.MELEE, Tag.AOE, Tag.DISARM]),
        halfCard([Tag.XP, Tag.DISCARD])),
    'Watch it Burn': new Skill('Watch it Burn', 9, 98, 
        halfCard([Tag.POISON, Tag.WOUND, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.WOUND, Tag.AOE]))
};

export default class Scoundrel extends Class {

    constructor() {
        super('Scoundrel', 9, skills);
    }
}
