import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Power Ballad': new Skill('Power Ballad', 1, 19,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.MOVE, Tag.STRENGTHEN, Tag.XP])),
    'Defensive Ditty': new Skill('Defensive Ditty', 1, 9,
        halfCard([Tag.SHIELD, Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.XP, Tag.SINGLE_ROUND_BUFF])),
    'Song of Speed': new Skill('Song of Speed', 1, 5,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.MUDDLE, Tag.XP])),
    'Tuning the Outcome': new Skill('Tuning the Outcome', 1, 78,
        halfCard([Tag.BLESS]), 
        halfCard([Tag.MOVE, Tag.CURSE])),
    'Call to Action': new Skill('Call to Action', 1, 85,
        halfCard([Tag.STRENGTHEN]), 
        halfCard([])),
    'Warding Dagger': new Skill('Warding Dagger', 1, 56,
        halfCard([Tag.MELEE, Tag.IMMOBILIZE]), 
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.XP, Tag.SINGLE_ROUND_BUFF, Tag.DISCARD])),
    'Throw Voice': new Skill('Throw Voice', 1, 44,
        halfCard([Tag.DISARM, Tag.AOE]), 
        halfCard([Tag.XP, Tag.DISCARD])),
    'Singing Arrow': new Skill('Singing Arrow', 1, 89,
        halfCard([Tag.CURSE, Tag.AOE]), 
        halfCard([Tag.RANGED, Tag.WOUND])),
    'Marching Beat': new Skill('Marching Beat', 1, 32,
        halfCard([]), 
        halfCard([Tag.MOVE])),
    'Wistful Wounding': new Skill('Wistful Wounding', 0, 16,
        halfCard([Tag.WOUND, Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP])),
    'Unending Chant': new Skill('Unending Chant', 0, 51,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.CURSE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Nimble Knife': new Skill('Nimble Knife', 0, 27,
        halfCard([Tag.MELEE, Tag.CURSE, Tag.BLESS]), 
        halfCard([Tag.MOVE])),
    'Soothing Lullaby': new Skill('Soothing Lullaby', 2, 11,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.HEAL, Tag.XP])),
    'Change Tempo': new Skill('Change Tempo', 2, 91,
        halfCard([Tag.IMMOBILIZE, Tag.AOE]), 
        halfCard([Tag.MOVE])),
    'Echoing Aria': new Skill('Echoing Aria', 3, 8,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.RETALIATE]), 
        halfCard([Tag.SHIELD, Tag.XP, Tag.SINGLE_ROUND_BUFF])),
    'Crippling Chorus': new Skill('Crippling Chorus', 3, 62,
        halfCard([Tag.STUN, Tag.AOE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.DISARM])),
    'Disorienting Dirge': new Skill('Disorienting Dirge', 4, 14,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.CURSE, Tag.BLESS, Tag.AOE, Tag.XP])),
    'Inspiring Anthem': new Skill('Inspiring Anthem', 4, 50,
        halfCard([]), 
        halfCard([])),
    'Melody and Harmony': new Skill('Melody and Harmony', 5, 78,
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.RANGED])),
    'Mobilizing Measure': new Skill('Mobilizing Measure', 5, 6,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.MOVE, Tag.XP])),
    'Pull the Strings': new Skill('Pull the Strings', 6, 20,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.XP])),
    'Provoke Terror': new Skill('Provoke Terror', 6, 60,
        halfCard([Tag.STUN, Tag.AOE]), 
        halfCard([Tag.RANGED, Tag.PUSH])),
    'Nightmare Serenade': new Skill('Nightmare Serenade', 7, 13,
        halfCard([Tag.CURSE, Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.RANGED, Tag.AOE, Tag.CURSE, Tag.XP])),
    'Booming Proclamation': new Skill('Booming Proclamation', 7, 65,
        halfCard([Tag.RANGED, Tag.AOE, Tag.PUSH]), 
        halfCard([Tag.XP, Tag.DISCARD])),
    'Tranquil Trill': new Skill('Tranquil Trill', 8, 10,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.DISARM, Tag.AOE, Tag.XP])),
    'Commanding Presence': new Skill('Commanding Presence', 8, 59,
        halfCard([]), 
        halfCard([Tag.XP, Tag.DISCARD])),
    'Captivating Performance': new Skill('Captivating Performance', 9, 25,
        halfCard([Tag.XP, Tag.MULTI_ROUND_BUFF]), 
        halfCard([Tag.STUN, Tag.AOE, Tag.XP])),
    'Shadow Puppets': new Skill('Shadow Puppets', 9, 52,
        halfCard([Tag.MOVE, Tag.JUMP]), 
        halfCard([]))
};

export default class Soothsinger extends Class {

    constructor() {
        super('Soothsinger', 9, HitpointsScaling.SQUISHY, true, skills);
    }
}
