import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Fire Orbs': new Skill('Fire Orbs', 1, 69, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP, Tag.GENERATE_FIRE, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Impaling Eruption': new Skill('Impaling Eruption', 1, 70, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP, Tag.GENERATE_EARTH, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Reviving Ether': new Skill('Reviving Ether', 1, 80, 
        halfCard([Tag.GENERATE_DARK, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.JUMP])),
    'Freezing Nova': new Skill('Freezing Nova', 1, 21, 
        halfCard([Tag.MELEE, Tag.AOE, Tag.CONSUME_ICE, Tag.IMMOBILIZE]), 
        halfCard([Tag.HEAL, Tag.GENERATE_LIGHT, Tag.DISCARD])),
    'Mana Bolt': new Skill('Mana Bolt', 1, 7, 
        halfCard([Tag.RANGED, ...Tag.CONSUME_ANY, Tag.XP]), 
        halfCard([Tag.HEAL])),
    'Frost Armor': new Skill('Frost Armor', 1, 20, 
        halfCard([Tag.RANGED, Tag.XP, ...Tag.CONSUME_ANY]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.GENERATE_ICE, Tag.XP, Tag.DISCARD])),
    'Flame Strike': new Skill('Flame Strike', 1, 36, 
        halfCard([Tag.RANGED, Tag.CONSUME_FIRE, Tag.WOUND]), 
        halfCard([Tag.RANGED, Tag.XP])),
    'Ride the Wind': new Skill('Ride the Wind', 1, 83, 
        halfCard([Tag.LOOT]), 
        halfCard([Tag.MOVE, Tag.JUMP, Tag.GENERATE_AIR, Tag.DISCARD])),
    'Crackling Air': new Skill('Crackling Air', 0, 25, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.CONSUME_AIR, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.CONSUME_FIRE, Tag.RETALIATE, Tag.SINGLE_ROUND_BUFF])),
    'Hardened Spikes': new Skill('Hardened Spikes', 0, 26, 
        halfCard([Tag.RETALIATE, Tag.AOE, Tag.CONSUME_EARTH, Tag.XP, Tag.SINGLE_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.CONSUME_ICE, Tag.SHIELD, Tag.SINGLE_ROUND_BUFF])),
    'Aid from the Ether': new Skill('Aid from the Ether', 0, 91, 
        halfCard([Tag.HEAL]), 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD])),
    'Flashing Burst': new Skill('Flashing Burst', 2, 26, 
        halfCard([Tag.RANGED, Tag.GENERATE_LIGHT]), 
        halfCard([Tag.MOVE])),
    'Icy Blast': new Skill('Icy Blast', 2, 66, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.MUDDLE, Tag.GENERATE_ICE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.HEAL, Tag.DISCARD])),
    'Cold Fire': new Skill('Cold Fire', 3, 67, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_FIRE, Tag.CONSUME_ICE, Tag.STUN]), 
        halfCard([Tag.LOOT, Tag.DISCARD])),
    'Elemental Aid': new Skill('Elemental Aid', 3, 84, 
        halfCard([Tag.HEAL, Tag.CONSUME_EARTH, Tag.XP]), 
        halfCard([Tag.SHIELD, Tag.CONSUME_AIR, Tag.AOE, Tag.SINGLE_ROUND_BUFF])),
    'Spirit of Doom': new Skill('Spirit of Doom', 4, 81, 
        halfCard([Tag.CURSE, Tag.CONSUME_DARK, Tag.INSTA_KILL, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.HEAL, Tag.XP, Tag.CONSUME_LIGHT, Tag.DISCARD])),
    'Forked Beam': new Skill('Forked Beam', 4, 20, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP]), 
        halfCard([Tag.MOVE])),
    'Chromatic Explosion': new Skill('Chromatic Explosion', 5, 71, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.GENERATE_AIR, Tag.GENERATE_DARK, Tag.GENERATE_EARTH, Tag.GENERATE_FIRE, Tag.GENERATE_ICE, Tag.GENERATE_LIGHT, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, ...Tag.GENERATE_ANY])),
    'Engulfed in Flames': new Skill('Engulfed in Flames', 5, 44, 
        halfCard([Tag.RANGED, Tag.GENERATE_FIRE]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.RETALIATE, Tag.XP, Tag.DISCARD])),
    'Living Torch': new Skill('Living Torch', 6, 96, 
        halfCard([Tag.RANGED, Tag.IMMOBILIZE, Tag.CONSUME_LIGHT, Tag.XP]), 
        halfCard([Tag.SUMMON, Tag.XP, Tag.GENERATE_FIRE, Tag.DISCARD])),
    'Frozen Night': new Skill('Frozen Night', 6, 46, 
        halfCard([Tag.MELEE, Tag.XP, Tag.AOE, Tag.GENERATE_ICE, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.CONSUME_DARK, Tag.INVISIBLE, Tag.XP])),
    'Twin Restoration': new Skill('Twin Restoration', 7, 75, 
        halfCard([Tag.DISCARD]), 
        halfCard([Tag.HEAL, Tag.AOE])),
    'Stone Fists': new Skill('Stone Fists', 7, 62, 
        halfCard([Tag.MELEE, Tag.PUSH, Tag.IMMOBILIZE, Tag.CONSUME_EARTH, Tag.AOE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.SHIELD, Tag.CONSUME_EARTH, Tag.XP, Tag.SINGLE_ROUND_BUFF])),
    'Zephyr Wings': new Skill('Zephyr Wings', 8, 85, 
        halfCard([Tag.LOOT, Tag.CONSUME_AIR, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.JUMP, Tag.CONSUME_AIR, Tag.XP, Tag.DISCARD])),
    'Cold Front': new Skill('Cold Front', 8, 61, 
        halfCard([Tag.RANGED, Tag.GENERATE_ICE, Tag.XP, Tag.AOE, Tag.DISCARD]), 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.RETALIATE, Tag.XP, Tag.DISCARD])),
    'Black Hole': new Skill('Black Hole', 9, 41, 
        halfCard([Tag.RANGED, Tag.XP, Tag.AOE, Tag.CONSUME_DARK, Tag.INSTA_KILL, Tag.DISCARD]), 
        halfCard([Tag.PULL, Tag.AOE])),
    'Inferno': new Skill('Inferno', 9, 19, 
        halfCard([Tag.RANGED, Tag.CONSUME_FIRE, Tag.XP]), 
        halfCard([Tag.RETALIATE, Tag.AOE, Tag.SINGLE_ROUND_BUFF]))
};

export default class Spellweaver extends Class {

    constructor() {
        super('Spellweaver', 8, HitpointsScaling.SQUISHY, false, skills);
    }
}
