import Class from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Forged Ferocity': new Skill('Forged Ferocity', 1, 96, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.SHIELD, Tag.GENERATE_EARTH, Tag.SINGLE_ROUND_BUFF])),
    'Wild Animation': new Skill('Wild Animation', 1, 92, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.GENERATE_AIR])),
    'Living Night': new Skill('Living Night', 1, 82, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.GENERATE_DARK, Tag.SINGLE_ROUND_BUFF])),
    'Unending Dominance': new Skill('Unending Dominance', 1, 98, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.DISCARD])),
    'Unwavering Hand': new Skill('Unwavering Hand', 1, 31, 
        halfCard([Tag.HEAL]), 
        halfCard([])),
    'Mighty Bond': new Skill('Mighty Bond', 1, 51, 
        halfCard([]), 
        halfCard([Tag.MOVE, Tag.JUMP])),
    'Bonded Might': new Skill('Bonded Might', 1, 61, 
        halfCard([]), 
        halfCard([Tag.LOOT])),
    'Biting Wind': new Skill('Biting Wind', 1, 25, 
        halfCard([Tag.RANGED, Tag.CONSUME_AIR, Tag.PUSH, Tag.XP]), 
        halfCard([Tag.HEAL])),
    'Black Fire': new Skill('Black Fire', 1, 24, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.CONSUME_FIRE, Tag.WOUND, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.MUDDLE])),
    'Leathery Wings': new Skill('Leathery Wings', 0, 90, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.STRENGTHEN])),
    'Volatile Flame': new Skill('Volatile Flame', 0, 94, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.RANGED, Tag.GENERATE_FIRE])),
    'Ethereal Vines': new Skill('Ethereal Vines', 0, 30, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.IMMOBILIZE]), 
        halfCard([Tag.MOVE, Tag.HEAL])),
    'Earthen Steed': new Skill('Earthen Steed', 2, 13, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.JUMP])),
    'Grasping the Void': new Skill('Grasping the Void', 2, 62, 
        halfCard([Tag.RANGED, Tag.CURSE, Tag.CONSUME_DARK, Tag.STUN, Tag.XP]), 
        halfCard([Tag.RANGED, Tag.HEAL])),
    'Tear the Fabric': new Skill('Tear the Fabric', 3, 41,
        halfCard([Tag.INSTA_KILL, Tag.AOE, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.HEAL, Tag.CONSUME_EARTH])),
    'Oozing Manifestation': new Skill('Oozing Manifestation', 3, 86, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.RANGED, Tag.IMMOBILIZE, Tag.CONSUME_DARK, Tag.CURSE, Tag.XP])),
    'Living Mountain': new Skill('Living Mountain', 4, 88, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.LOOT])),
    'Divided Mind': new Skill('Divided Mind', 4, 55, 
        halfCard([]), 
        halfCard([])),
    'Strength in Numbers': new Skill('Strength in Numbers', 5, 45, 
        halfCard([]), 
        halfCard([Tag.RANGED])),
    'Conjured Aid': new Skill('Conjured Aid', 5, 81, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.MOVE])),
    'Endless Spikes': new Skill('Endless Spikes', 6, 97, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.RETALIATE, Tag.SINGLE_ROUND_BUFF])),
    'Inexorable Momentum': new Skill('Inexorable Momentum', 6, 32, 
        halfCard([Tag.RANGED, Tag.PIERCE, Tag.CONSUME_AIR]), 
        halfCard([Tag.MOVE])),
    'Negative Energy': new Skill('Negative Energy', 7, 95, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([Tag.CURSE, Tag.GENERATE_DARK])),
    'Staff of Visions': new Skill('Staff of Visions', 7, 27, 
        halfCard([Tag.MELEE, Tag.MUDDLE, Tag.CONSUME_FIRE, Tag.WOUND, Tag.XP]), 
        halfCard([Tag.MOVE, Tag.STRENGTHEN])),
    'Intervening Apparitions': new Skill('Intervening Apparitions', 8, 68, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]), 
        halfCard([Tag.GENERATE_LIGHT])),
    'Otherworldly Rage': new Skill('Otherworldly Rage', 8, 35, 
        halfCard([]), 
        halfCard([Tag.MOVE])),
    'Interplanar Mastery': new Skill('Interplanar Mastery', 9, 22, 
        halfCard([Tag.DISCARD]), 
        halfCard([Tag.MOVE, Tag.JUMP])),
    'Horned Majesty': new Skill('Horned Majesty', 9, 80, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.MULTI_ROUND_BUFF, Tag.DISCARD]), 
        halfCard([]))
};

export default class Summoner extends Class {

    constructor() {
        super('Summoner', 11, true, skills);
    }
}
