import Class, { HitpointsScaling } from './Class';
import Skill from '../Skill';
import { Tag, halfCard } from '../Skill';

const skills = {
    'Proximity Mine': new Skill('Proximity Mine', 1, 62, 
        halfCard([Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Harmless Contraption': new Skill('Harmless Contraption', 1, 74, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.HEAL])),
    'Flamethrower': new Skill('Flamethrower', 1, 47, 
        halfCard([Tag.MELEE, Tag.AOE, Tag.WOUND, Tag.XP, Tag.GENERATE_FIRE, Tag.DISCARD]),
        halfCard([Tag.SHIELD, Tag.AOE, Tag.SINGLE_ROUND_BUFF])),
    'Hook Gun': new Skill('Hook Gun', 1, 72, 
        halfCard([Tag.RANGED, Tag.PULL]),
        halfCard([Tag.LOOT, Tag.XP, Tag.DISCARD])),
    'Ink Bomb': new Skill('Ink Bomb', 1, 74, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.XP, Tag.GENERATE_DARK, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Net Shooter': new Skill('Net Shooter', 1, 19, 
        halfCard([Tag.RANGED, Tag.AOE, Tag.IMMOBILIZE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.IMMOBILIZE, Tag.MOVE])),
    'Stun Shot': new Skill('Stun Shot', 1, 20, 
        halfCard([Tag.RANGED, Tag.STUN]),
        halfCard([Tag.MOVE])),
    'Reinvigorating Elixir': new Skill('Reinvigorating Elixir', 1, 37, 
        halfCard([Tag.HEAL]),
        halfCard([Tag.XP, Tag.DISCARD])),
    'Restorative Mist': new Skill('Restorative Mist', 1, 17, 
        halfCard([Tag.HEAL]),
        halfCard([Tag.MOVE, Tag.HEAL])),
    'Energizing Tonic': new Skill('Energizing Tonic', 1, 16, 
        halfCard([Tag.HEAL, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.XP, Tag.DISCARD])),
    'Enhancement Field': new Skill('Enhancement Field', 1, 61, 
        halfCard([Tag.RANGED]),
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Toxic Bolt': new Skill('Toxic Bolt', 1, 18, 
        halfCard([Tag.RANGED, Tag.POISON, Tag.GENERATE_EARTH]),
        halfCard([Tag.RANGED, Tag.XP, Tag.DISCARD])),
    'Reviving Shock': new Skill('Reviving Shock', 0, 34, 
        halfCard([Tag.RANGED, Tag.AOE]),
        halfCard([Tag.HEAL, Tag.XP, Tag.DISCARD])),
    'Volatile Concoction': new Skill('Volatile Concoction', 0, 76, 
        halfCard([]),
        halfCard([Tag.CONSUME_ICE])),
    'Potent Potables': new Skill('Potent Potables', 0, 46, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.HEAL, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Stamina Booster': new Skill('Stamina Booster', 2, 48, 
        halfCard([Tag.HEAL]),
        halfCard([Tag.XP, Tag.DISCARD])),
    'Disorienting Flash': new Skill('Disorienting Flash', 2, 73, 
        halfCard([Tag.STUN, Tag.AOE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MUDDLE, Tag.MOVE])),
    'Tinkerer\'s Tools': new Skill('Tinkerer\'s Tools', 3, 26, 
        halfCard([Tag.XP]),
        halfCard([])),
    'Crank Bow': new Skill('Crank Bow', 3, 66, 
        halfCard([Tag.RANGED, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Dangerous Contraption': new Skill('Dangerous Contraption', 4, 84, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE])),
    'Micro Bots': new Skill('Micro Bots', 4, 22, 
        halfCard([Tag.HEAL, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.LOOT, Tag.DISCARD])),
    'Noxious Vials': new Skill('Noxious Vials', 5, 75, 
        halfCard([]),
        halfCard([Tag.RANGED, Tag.AOE, Tag.POISON, Tag.XP, Tag.DISCARD])),
    'Disintegration Beam': new Skill('Disintegration Beam', 5, 36, 
        halfCard([Tag.AOE, Tag.INSTA_KILL, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.DISARM])),
    'Gas Canister': new Skill('Gas Canister', 6, 71, 
        halfCard([]),
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD])),
    'Auto Turret': new Skill('Auto Turret', 6, 34, 
        halfCard([Tag.MULTI_ROUND_BUFF, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.HEAL])),
    'Murderous Contraption': new Skill('Murderous Contraption', 7, 94, 
        halfCard([Tag.SUMMON, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.RANGED])),
    'Curative Aerosol': new Skill('Curative Aerosol', 7, 21, 
        halfCard([Tag.MOVE, Tag.HEAL]),
        halfCard([Tag.HEAL, Tag.AOE, Tag.XP, Tag.DISCARD])),
    'Jet Propulsion': new Skill('Jet Propulsion', 8, 38, 
        halfCard([]),
        halfCard([Tag.MOVE, Tag.JUMP, Tag.XP, Tag.DISCARD])),
    'Harsh Stimulants': new Skill('Harsh Stimulants', 8, 27, 
        halfCard([Tag.MELEE, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.SINGLE_ROUND_BUFF])),
    'Lethal Injection': new Skill('Lethal Injection', 9, 85, 
        halfCard([Tag.INSTA_KILL, Tag.XP, Tag.DISCARD]),
        halfCard([Tag.MOVE, Tag.POISON, Tag.AOE])),
    'Chimeric Formula': new Skill('Chimeric Formula', 9, 43, 
        halfCard([]),
        halfCard([Tag.XP, Tag.DISCARD]))
};

export default class Tinkerer extends Class {

    constructor() {
        super('Tinkerer', 12, HitpointsScaling.MIDRANGE, false, skills);
    }
}
